name: Build & Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1 Checkout the repo
      - uses: actions/checkout@v4

      # 2 Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3 Install dependencies
      - run: npm install

      # 4 Remove existing pages and clear cache
      - name: delete cache
        run: rm -rf .cache

      # 5 Build Eleventy site
      - name: Build Eleventy
        run: npm run build && npx @11ty/eleventy 
        
      # 6 Add .nojekyll to ignore Jekyll
      - name: Disable Jekyll
        run: touch docs/.nojekyll

      # 7 Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
